### ISSUE TITLE
Combo Slider

### ISSUE THREAD

**Issue by sunglassesmichael** [tamadra/s-rank#2]
For Ancient Light it won't let me move the combos up past 8

**Comment by tamadra** [comment]
The range for Ancient Light has been changed from 4 (min) to 10 (max). Is that good?

**Comment by sunglassesmichael** [comment]
I guess. Since it's Tricolor, I imagine some people will score more than 10, but 10 at least get's you to S-Rank for a rarity of 4.7. Thanks.

**Comment by tamadra** [comment]
It's a little bit of a balance from a usability point-of-view. I've noticed when the range gets expanded too much, the slider becomes too sensitive, especially on mobile devices. Moving the slider small amounts jumps the combo value to the point it becomes difficult to dial in the value you want.
I'm definitely open to thoughts/suggestions on making it better.
Also my reasoning for capping it at 10 is that folks making 10+ combos probably are not having a hard time achieving the S rank :)

**Comment by sunglassesmichael** [comment]
Ah. That makes sense and sounds pretty reasonable. :D
