### ISSUE TITLE
Update monster database?

### ISSUE THREAD

**Issue by nhex** [tamadra/s-rank#4]
Can you update the monster database? It's been out of date for a while, missing some monsters such as Shining Lance Wielder, Odin, so it's about 5-6months out of date for NA. Hopefully you can update skill-up as well from the same data.

**Comment by tamadra** [comment]
Yes, I have been meaning to!
Had actually wanted to consolidate the skill-up/s-rank/iconify database of monsters, since they were all on separate systems. Hopefully they'll get updated at the same time.

**Comment by tamadra** [comment]
OK, both S-Rank and Skill Up calculators have been updated with the latest monster database.

**Comment by nhex** [comment]
Thanks! You do good work!
