### ISSUE TITLE
file upload failed

### ISSUE THREAD

**Issue by fmchao** [tamadra/s-rank#5]
when I attempt to upload my screenshot for s-rank, it just says file upload failed.

**Comment by tamadra** [comment]
What browser were you on? Thanks.

**Comment by fmchao** [comment]
Chrome on Android 4.4.

**Comment by tamadra** [comment]
File upload re-written to be more mobile friendly.

**Comment by fmchao** [comment]
![bug](https://cloud.githubusercontent.com/assets/3487181/6363009/fac699f6-bc47-11e4-9b33-498d8267b768.jpg)

Still having this issue, different bug.

**Comment by tamadra** [comment]
413 Request Entity Too Large. Looks like file limit size on my server was configured too small. I bumped it up - I think it should work now. 
Please try again and let me know. Thanks.

**Comment by fmchao** [comment]
Seems to have worked. Said it should show shortly. Thanks for your work.

**Comment by tamadra** [comment]
Great! Yeah, should be up shortly.
